name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: https://gitea.ocram85.com/actions/metadata-action@v5
        with:
          images: |
            gitea.ocram85.com/ocram85/swarmproxy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: https://gitea.ocram85.com/actions/setup-buildx-action@v3
      -
        name: Login to Gitea Package Registry
        uses: https://gitea.ocram85.com/actions/login-action@v3
        with:
          registry: gitea.ocram85.com
          username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push
        uses: https://gitea.ocram85.com/actions/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
