name: docker

run-name: Container Image Deployment

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build-container:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: actions/metadata-action@v4
        with:
          images: |
            ocram85/swarmproxy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: actions/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v2
      -
        name: Login to Gitea Package Registry
        uses: actions/login-action@v2
        with:
          registry: gitea.ocram85.com
          username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          password: ${{ secrets.TOKEN }}
      -
        name: Build and push
        uses: actions/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #tags: gitea.ocram85.com/ocram85/swarmproxy:next2

