name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: https://gitea.ocram85.com/actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup go
        uses: https://gitea.ocram85.com/actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: Use Go Action
        id: use-go-action
        uses: https://gitea.ocram85.com/actions/release-action@main
        with:
          files: |-
            CHANGELOG.md
          api_key: '${{ secrets.TOKEN }}'
          body: |
            > :bulb: **Note:** See [CHANGELOG.md](src/branch/main/CHANGELOG.md) for recent changes.
