version: "3.8"

networks:
  egress:
   attachable: true
  backend:
    internal: true

services:
  swarmproxy:
    image: gitea.ocram85.com/ocram85/swarmproxy:latest
    deploy:
      replicas: 1
    environment:
      - LOGLEVEL=Info
    networks:
      egress:
        aliases:
          - proxy

  curl:
    image: curlimages/curl:8.1.2
    command: ["-I", "-x", "proxy:8888", "https://google.com"]
    depends_on:
      - swarmproxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    networks:
      - backend
      - egress
